apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: site

global:
  # These values are replaced on cluster creation by workflow
  clusterName: f99ae090
  sshKeyName: tks-seoul
  clusterRegion: ap-northeast-2
  mdNumOfAz: 3
  mdMinSizePerAz: 1
  mdMaxSizePerAz: 5
  mdMachineType: t3.large
charts:
- name: cluster-api-aws
  override:
    sshKeyName: $(sshKeyName)
    cluster.name: $(clusterName)
    cluster.region: $(clusterRegion)
    cluster.bastion.enabled: true
    machinePool:
    - name: taco
      machineType: t3.2xlarge
      replicas: 3
      minSize: 1
      maxSize: 16
      rootVolume:
        size: 200
        type: gp2
      labels:
        taco-lma: enabled
        servicemesh: enabled
        taco-ingress-gateway: enabled
    machineDeployment:
    - name: normal
      numberOfAZ: $(mdNumOfAz)
      minSizePerAZ: $(mdMinSizePerAz)
      maxSizePerAZ: $(mdMaxSizePerAz)
      selector:
        matchLabels:
      machineType: $(mdMachineType)
      rootVolume:
        size: 50
        type: gp2

- name: aws-ebs-csi-driver
  override:
